{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "83bb4632",
   "metadata": {},
   "outputs": [],
   "source": [
    "from skimage import io\n",
    "import scipy.ndimage as ndi\n",
    "import random\n",
    "from tqdm import tqdm\n",
    "import numpy as np\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import roc_curve, auc, jaccard_score\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.spatial.distance import dice\n",
    "\n",
    "from pathlib import Path\n",
    "import os\n",
    "\n",
    "from tqdm.notebook import tqdm\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "74dc6f71",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "from torch import nn\n",
    "from torch.utils.data import DataLoader\n",
    "from torchvision import datasets\n",
    "from torchvision.transforms import ToTensor, Lambda, Compose\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, precision_recall_curve"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "32ea5eba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading segments to /users/shrey2/Documents/NDD/brainlit/docs/notebooks/utils/data\n"
     ]
    }
   ],
   "source": [
    "data_dir = \"/users/shrey2/Documents/NDD/brainlit/docs/notebooks/utils/data\"\n",
    "print(f\"Downloading segments to {data_dir}\")\n",
    "if not os.path.exists(data_dir):\n",
    "    os.makedirs(data_dir)\n",
    "\n",
    "im_dir = Path(os.path.join(data_dir, \"sample-tif-location\"))\n",
    "if not os.path.exists(im_dir):\n",
    "    os.makedirs(im_dir)\n",
    "\n",
    "swc_dir = os.path.join(data_dir, \"sample-swc-location\")\n",
    "if not os.path.exists(swc_dir):\n",
    "    os.makedirs(swc_dir)\n",
    "\n",
    "mask_dir = Path(os.path.join(data_dir, \"mask-location\"))\n",
    "\n",
    "swc_base_path = Path(swc_dir) / \"Manual-GT\"\n",
    "\n",
    "gfp_files = list(im_dir.glob(\"**/*-gfp.tif\"))\n",
    "\n",
    "ms = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8911c3c6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "79fc0db9bc2942e587eaf4c4adb40812",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/50 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "X_torch = []\n",
    "y_torch = []\n",
    "\n",
    "for i, im_path in enumerate(tqdm(gfp_files)):\n",
    "\n",
    "    f = im_path.parts[-1][:-8].split(\"_\")\n",
    "    image = f[0]\n",
    "    num = int(f[1])\n",
    "\n",
    "    if (image == \"test\" and num in [9,10,24]) or (image == \"validation\" and num in [11]):\n",
    "        continue\n",
    "\n",
    "    #getting image\n",
    "    im = io.imread(im_path, plugin=\"tifffile\")\n",
    "    im = (im - np.amin(im)) / (np.amax(im) - np.amin(im))\n",
    "    im = np.swapaxes(im,0,2)\n",
    "    im_padded = np.pad(im, ((4,4), (4,4), (3,3)) )\n",
    "    \n",
    "    #getting ground truth mask\n",
    "    file_name = str(im_path)[str(im_path).find(\"\\\\\", 80) + 1 : (str(im_path).find(\"sample\"))] + \"/mask-location/\"\n",
    "    file_num = file_name[file_name.find(\"_\")+1:]\n",
    "    if file_name[0] == 'v':\n",
    "        file_num = str(int(file_num)+25)\n",
    "    mask_path = Path(file_name + f[0] + \"_\" + f[1] + \"_mask.npy\")\n",
    "    mask = np.load(mask_path)\n",
    "    \n",
    "    X_torch.append(im)\n",
    "    y_torch.append(mask)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a07636b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_torch = np.reshape(X_torch, (1, 46, 330, 330, 100)) #making it 5 channels for the 3d cnn\n",
    "y_torch = np.reshape(y_torch, (1, 46, 330, 330, 100))\n",
    "\n",
    "X_torch_train = X_torch[:, 0:23] #50/50 train test split\n",
    "y_torch_train = y_torch[:, 0:23]\n",
    "x_torch_test = X_torch[:, 23:46]\n",
    "y_torch_test = y_torch[:, 23:46]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0c8a35d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "training_data = torch.tensor([X_torch_train, y_torch_train]).float()\n",
    "test_data = torch.tensor([x_torch_test, y_torch_test]).float()\n",
    "\n",
    "batch_size = 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "49a21dc9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create data loaders.\n",
    "train_dataloader = DataLoader(training_data, batch_size=batch_size)\n",
    "test_dataloader = DataLoader(test_data, batch_size=batch_size)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "34e020d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Feature batch shape: torch.Size([1, 23, 330, 330, 100])\n",
      "Labels batch shape: torch.Size([1, 23, 330, 330, 100])\n",
      "Using cpu device\n"
     ]
    }
   ],
   "source": [
    "train_features, train_labels = next(iter(train_dataloader))\n",
    "print(f\"Feature batch shape: {train_features.size()}\")\n",
    "print(f\"Labels batch shape: {train_labels.size()}\")\n",
    "\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "print('Using {} device'.format(device))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "558d9b14",
   "metadata": {},
   "source": [
    "## Pytorch Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "94d35441",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NeuralNetwork(\n",
      "  (linear_relu_stack): Sequential(\n",
      "    (0): Conv3d(1, 1, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))\n",
      "  )\n",
      ")\n"
     ]
    }
   ],
   "source": [
    "class NeuralNetwork(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(NeuralNetwork, self).__init__()\n",
    "        self.linear_relu_stack = nn.Sequential(\n",
    "            nn.Conv3d(1, 1, kernel_size = 3, stride = 1, padding = 1),\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        logits = self.linear_relu_stack(x)\n",
    "        self.Sigmoid = nn.Sigmoid()\n",
    "        logits = self.Sigmoid(logits)\n",
    "        return logits\n",
    "    \n",
    "model = NeuralNetwork().to(device)\n",
    "print(model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fbb0162a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_loop(dataloader, model, loss_fn, optimizer):\n",
    "    size = len(dataloader.dataset)\n",
    "    y_true = []\n",
    "    y_pred = []\n",
    "    for batch, (X_all, y_all) in enumerate(dataloader):\n",
    "        \n",
    "        loss_list = []\n",
    "\n",
    "        for image in range(X_all.shape[1]):\n",
    "            X = np.reshape(X_all[0][image], (1, 1, 330, 330, 100))\n",
    "            y = np.reshape(y_all[0][image], (1, 1, 330, 330, 100))\n",
    "            \n",
    "            # Compute prediction and loss\n",
    "            optimizer.zero_grad()\n",
    "            pred = model(X)\n",
    "            pred = torch.squeeze(pred, 3).clone()\n",
    "            loss = loss_fn(pred, y)\n",
    "\n",
    "            # Backpropagation\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            loss, current = loss.item(), batch * len(X)\n",
    "            loss_list.append(loss)\n",
    "            \n",
    "        print(\"Avg loss:\", np.average(loss_list))\n",
    "\n",
    "\n",
    "def test_loop(dataloader, model, loss_fn, print_acc):\n",
    "    size = 330*330*100*14\n",
    "    print(\"Size: \", size)\n",
    "    num_batches = len(dataloader)\n",
    "    \n",
    "    for batch, (X_all, y_all) in enumerate(dataloader):\n",
    "\n",
    "        test_loss, correct = 0, 0\n",
    "\n",
    "        y_true = []\n",
    "        y_pred = []\n",
    "        y_list = []\n",
    "        x_list = []\n",
    "\n",
    "        with torch.no_grad():\n",
    "            for image in range(X_all.shape[1]):\n",
    "                X = np.reshape(X_all[0][image], (1, 1, 330, 330, 100))\n",
    "                y = np.reshape(y_all[0][image], (1, 1, 330, 330, 100))\n",
    "                pred = model(X)\n",
    "                pred = torch.squeeze(pred, 3)\n",
    "                \n",
    "                x_list.append(X)\n",
    "                y_list.append(y)\n",
    "                y_pred.append(pred)\n",
    "                \n",
    "                test_loss += loss_fn(pred, y).item()\n",
    "    \n",
    "    #test acc\n",
    "  #  if print_acc == True:\n",
    "  #      acc_list = []\n",
    "  #      i = 0\n",
    "  #      while i < len(y_pred):\n",
    "  #          pred_r = np.round(y_pred[i].detach().numpy()).flatten()\n",
    "  #          target = np.array(y_list[i]).astype(int).flatten()\n",
    "  #          acc = accuracy_score(pred_r, target)\n",
    "  #          acc_list.append(acc)\n",
    "        \n",
    "        #pred_r = np.round(y_pred.flatten().detach())\n",
    "        #target = np.array(y_list).flatten().astype(int)\n",
    "        #pred_r = np.round(pred.detach().numpy()).flatten()\n",
    "        #target = np.array(y).astype(int).flatten()\n",
    "        #acc = accuracy_score(pred_r, target)\n",
    "  #      print(\"Test accuracy: \", np.mean(acc_list))\n",
    "    \n",
    "    return x_list, y_pred, y_list, test_loss\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e8011318",
   "metadata": {},
   "outputs": [],
   "source": [
    "#PyTorch\n",
    "class DiceLoss(nn.Module):\n",
    "    def __init__(self, weight=None, size_average=True):\n",
    "        super(DiceLoss, self).__init__()\n",
    "\n",
    "    def forward(self, inputs, targets, smooth=1):\n",
    "        \n",
    "        #comment out if your model contains a sigmoid or equivalent activation layer\n",
    "        #inputs = F.sigmoid(inputs)       \n",
    "        \n",
    "        #flatten label and prediction tensors\n",
    "        inputs = inputs.view(-1)\n",
    "        targets = targets.view(-1)\n",
    "        \n",
    "        intersection = (inputs * targets).sum()                            \n",
    "        dice = (2.*intersection + smooth)/(inputs.sum() + targets.sum() + smooth)  \n",
    "        \n",
    "        return 1 - dice"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "0fe289f8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e990e642849347de8e8b10c1c1a4cecb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/10 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952756881714\n",
      "Size:  152460000\n",
      "Epoch 2\n",
      "-------------------------------\n",
      "Avg loss: 0.993795273096665\n",
      "Size:  152460000\n",
      "Epoch 3\n",
      "-------------------------------\n",
      "Avg loss: 0.993795273096665\n",
      "Size:  152460000\n",
      "Epoch 4\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952705051588\n",
      "Size:  152460000\n",
      "Epoch 5\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952705051588\n",
      "Size:  152460000\n",
      "Epoch 6\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952679136525\n",
      "Size:  152460000\n",
      "Epoch 7\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952679136525\n",
      "Size:  152460000\n",
      "Epoch 8\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952627306399\n",
      "Size:  152460000\n",
      "Epoch 9\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952601391337\n",
      "Size:  152460000\n",
      "Epoch 10\n",
      "-------------------------------\n",
      "Avg loss: 0.9937952601391337\n",
      "Size:  152460000\n",
      "Done!\n"
     ]
    }
   ],
   "source": [
    "#weights = torch.tensor([.75, .25])\n",
    "#from torchgeometry.losses.dice import DiceLoss\n",
    "\n",
    "#loss_fn = nn.BCELoss()\n",
    "loss_fn = DiceLoss()\n",
    "learning_rate = 0.0001\n",
    "optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)\n",
    "epochs = 10\n",
    "\n",
    "pred_list = []\n",
    "y_list = []\n",
    "loss_list = []\n",
    "\n",
    "\n",
    "for t in tqdm(range(epochs)):\n",
    "    print(f\"Epoch {t+1}\\n-------------------------------\")\n",
    "    train_loop(train_dataloader, model, loss_fn, optimizer)\n",
    "    if (epochs % 5 == 0):\n",
    "        print_acc = True\n",
    "    else:\n",
    "        print_acc = False\n",
    "    x_list, y_pred, y, loss = test_loop(test_dataloader, model, loss_fn, print_acc)\n",
    "    pred_list.append(y_pred)\n",
    "    y_list.append(y)\n",
    "    loss_list.append(loss)\n",
    "print(\"Done!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "9631bd3a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "cc758854248246ff82d3af2d4b6525b2",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/10 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "880ecf46403b471e813daa868e7adb2b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "57571c73d33e44a2b1f07e26c0b4b110",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2e956f5ed7684d6b89c89644b3a73b2b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3214256e497044e9be8bfa4ed63a108d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e5a3712ed83846c28916987d14d58b83",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2c476386e1b041a98e96eb5d68bfca40",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c56b9d208dbf43cfb52c892e95e3e900",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7dd40dd65c784609a9dcafb547cca3d3",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7dc433f2f9ee41ad98eeb54ca1389083",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c52ed3109206461b9e7376813e87cd51",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/23 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# getting accuracy, precision, recall at each epoch\n",
    "\n",
    "acc_list = []\n",
    "precision_list = []\n",
    "recall_list = []\n",
    "\n",
    "for i in tqdm(range(len(pred_list))):\n",
    "    acc_list_t = []\n",
    "    precision_list_t = []\n",
    "    recall_list_t = []\n",
    "    \n",
    "    for j in tqdm(range(len(pred_list[0]))):\n",
    "        pred = pred_list[i][j].clone().numpy()[:, 0].round().astype(int).flatten()\n",
    "        target = y_list[i][j][:, 0].clone().numpy().astype(int).flatten()\n",
    "\n",
    "        acc = accuracy_score(target, pred) * 100\n",
    "        acc_list_t.append(acc)\n",
    "\n",
    "        pr = precision_score(target, pred) * 100\n",
    "        precision_list_t.append(pr)\n",
    "\n",
    "        rc = recall_score(target, pred) * 100\n",
    "        recall_list_t.append(rc)\n",
    "        \n",
    "    mean_acc = np.mean(acc_list_t)\n",
    "    mean_pr = np.mean(precision_list_t)\n",
    "    mean_rc = np.mean(recall_list_t)\n",
    "    \n",
    "    acc_list.append(mean_acc)\n",
    "    precision_list.append(mean_pr)\n",
    "    recall_list.append(mean_rc)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "07f6731c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Quick test stats\n",
    "\n",
    "def get_stats(stat, epoch, acc_list, precision_list, recall_list):\n",
    "    if stat == \"accuracy\":\n",
    "        print(\"Accuracy at epoch \" + str(epoch) + \" is \" + str(acc_list[epoch - 1]))\n",
    "    if stat == \"all\":\n",
    "        print(\"Accuracy at epoch \" + str(epoch) + \" is \" + str(acc_list[epoch - 1]))\n",
    "        print(\"Precision at epoch \" + str(epoch) + \" is \" + str(precision_list[epoch - 1]))\n",
    "        print(\"Recall at epoch \" + str(epoch) + \" is \" + str(recall_list[epoch - 1]))\n",
    "        \n",
    "get_stats(\"all\", 2, acc_list, precision_list, recall_list)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4df57fea",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure()\n",
    "plt.title(\"Test loss over epoch\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Test loss\")\n",
    "plt.plot(loss_list)\n",
    "\n",
    "plt.figure()\n",
    "plt.title(\"Accuracy over epoch\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Avg accuracy (%)\")\n",
    "plt.plot(acc_list)\n",
    "\n",
    "plt.figure()\n",
    "plt.title(\"Precision over epoch\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Avg precision (%)\")\n",
    "plt.plot(precision_list)\n",
    "\n",
    "plt.figure()\n",
    "plt.title(\"Recall over epoch\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Avg recall (%)\")\n",
    "plt.plot(recall_list)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4155385a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "acc_list_t"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7321ec5",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "# Accuracy histogram on last epoch\n",
    "\n",
    "plt.figure()\n",
    "plt.title(\"Accuracy histogram for individual 23 images on last epoch\")\n",
    "plt.ylabel(\"Individual Accuracy\")\n",
    "plt.hist(acc_list_t, bins = 20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8b6386ad",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 0:  0.4813292\n",
      "Optimal Threshold for image 1:  0.48879603\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(120, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(120, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 2:  0.48569155\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(161, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(161, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 3:  0.48149103\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(200, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(200, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 4:  0.48195323\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(239, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(239, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 5:  0.4820033\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(278, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(278, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 6:  0.48155692\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(317, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(317, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 7:  0.48152474\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_Exception in callback BaseAsyncIOLoop._handle_events(356, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(356, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 8:  0.4880304\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(395, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(395, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 9:  0.48267302\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(434, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(434, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 10:  0.4855357\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(472, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(472, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 11:  0.48116392\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(512, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(512, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 12:  0.48119318\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(551, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(551, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 13:  0.48149678\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(590, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(590, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 14:  0.48900756\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(629, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(629, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 15:  0.4819097\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(668, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(668, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 16:  0.48162946\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(707, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(707, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 17:  0.48406285\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_Exception in callback BaseAsyncIOLoop._handle_events(746, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(746, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 18:  0.48327488\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(785, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(785, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 19:  0.4841251\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(822, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(822, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Context leak detected, msgtracer returned -1\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(862, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(862, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 20:  0.48557067\n",
      "Optimal Threshold for image 21:  0.48140803\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(902, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(902, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold for image 22:  0.48226443\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(940, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(940, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "Exception in callback BaseAsyncIOLoop._handle_events(980, 1)\n",
      "handle: <Handle BaseAsyncIOLoop._handle_events(980, 1)>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 189, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 580, in _check_running\n",
      "    raise RuntimeError(\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_events.py\", line 618, in run_until_complete\n",
      "    self._check_running()\n",
      "  File \"/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/asyncio/base_"
     ]
    }
   ],
   "source": [
    "# Plot all images/predictions from last epoch\n",
    "\n",
    "from sklearn.metrics import roc_curve, precision_recall_curve, auc\n",
    "\n",
    "for i in range(len(y_list[len(y_list) - 1])):\n",
    "    x = x_list[i].clone()[:,0].numpy()\n",
    "    pred = pred_list[len(pred_list) - 1][i].clone()[:,0].numpy()\n",
    "    y = y_list[len(y_list) - 1][i].clone()[:,0].numpy()\n",
    "    \n",
    "    fpr, tpr, thresholds = roc_curve(y.flatten(), pred.flatten())\n",
    "    optimal_thresh = thresholds[np.argmax(tpr - fpr)]\n",
    "    print(\"Optimal Threshold for image \" + str(i) + \": \", optimal_thresh)\n",
    "    \n",
    "    pred_thresh = pred\n",
    "    \n",
    "    for i in range(1):\n",
    "        for a in range(330):\n",
    "            for b in range(330):\n",
    "                for c in range(100):\n",
    "                    if pred[i][a][b][c]  > optimal_thresh:\n",
    "                        pred_thresh[i][a][b][c] = 1\n",
    "                    else:\n",
    "                        pred_thresh[i][a][b][c] = 0\n",
    "\n",
    "\n",
    "    import napari\n",
    "    with napari.gui_qt():\n",
    "        viewer = napari.Viewer(ndisplay=3)\n",
    "        viewer.add_image(x[0])\n",
    "        viewer.add_labels(y[0].astype(int))\n",
    "        viewer.add_labels(pred_thresh[0].astype(int), num_colors = 2)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "e2a9e603",
   "metadata": {},
   "outputs": [],
   "source": [
    "#metrics for one image\n",
    "\n",
    "#pred_0 = pred.clone().numpy()[:, 0].round().astype(int).flatten()\n",
    "#target_0 = y_torch_test[:, 0].astype(int).flatten()\n",
    "\n",
    "#print(\"Accuracy: \", accuracy_score(target_0, pred_0) * 100)\n",
    "#print(\"Precision: \", precision_score(target_0, pred_0) * 100)\n",
    "#print(\"Recall: \", recall_score(target_0, pred_0) * 100)\n",
    "#print(\"Nonzeros: \", np.count_nonzero(pred_0) * 100)\n",
    "#print(\"Nonzeros percent: \", np.count_nonzero(pred_0) / len(target_0) * 100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "50fa7478",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimal Threshold:  0.53039104\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x7fe5a41a7b80>"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEWCAYAAABrDZDcAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAApGElEQVR4nO3dd3hUZfr/8fdNDSWABlBaJPRmaBEUG7Y1ooJ90a9f18quLuuuq6xYwIK9rfW79mXVFUWkioCrgr3BIiEJLYQWWkIvIaTdvz8m+osIJJDMTCbzeV0X1zXnzDMz90lIPnnOc87zmLsjIiLRq0a4CxARkfBSEIiIRDkFgYhIlFMQiIhEOQWBiEiUUxCIiEQ5BYGISJRTEIgchJmtNLM9ZrbLzDaY2Vgza1jq+QFm9qmZ7TSz7WY2zcy67fMejczsaTNbXfI+y0u2m4b+iER+TUEgUrbz3b0h0AvoDdwBYGYnAB8BU4CWQAKwAPjKzNqVtKkDfAJ0B5KBRsAJwGagX0iPQuQATHcWixyYma0Ernf3j0u2HwO6u/u5ZvYFsNDdb9rnNTOAHHe/ysyuBx4E2rv7rhCXL1Iu6hGIlJOZtQbOATLMrD4wAHhvP03HA2eVPD4TmKkQkKpMQSBStslmthNYA2QD9wBHEvj5Wb+f9uuBn87/xx2gjUiVoSAQKdsF7h4LDAS6EPglvxUoBlrsp30LYFPJ480HaCNSZSgIRMrJ3T8DxgJPuPtu4Bvg0v00vYzAADHAx8DZZtYgJEWKHAYFgciheRo4y8x6AiOB35nZzWYWa2ZHmNkDBK4Kuq+k/ZsETim9b2ZdzKyGmcWZ2Z1mNigsRyCyDwWByCFw9xzgDWC0u38JnA1cRGAcYBWBy0tPcvdlJe33EhgwXgz8B9gBfE/g9NJ3IT8Akf3Q5aMiIlFOPQIRkSinIBARiXIKAhGRKKcgEBGJcrXCXcChatq0qbdt2zbcZYiIRJR58+Ztcvdm+3su4oKgbdu2zJ07N9xliIhEFDNbdaDndGpIRCTKKQhERKKcgkBEJMopCEREopyCQEQkygUtCMzsdTPLNrPUAzxvZvasmWWYWYqZ9QlWLSIicmDB7BGMJbBY94GcA3Qs+TcM+EcQaxERkQMIWhC4++fAloM0GQK84QHfAk3MTCs5iYjso7ComIc/XMS6bXuC8v7hHCNoRWDBjp9klez7FTMbZmZzzWxuTk5OSIoTEakKsrbmctlL3/DS55l8smhjUD4jIu4sdveXgZcBkpKStICCiFR77s60lPXcNXEhRe48M7QXQ3rt92/lCgtnEKwF2pTabl2yT0Qkqm3LzeeuyalMT1lPzzZNeG5ob+Lj6gft88IZBFOB4Wb2DtAf2O7u68NYj4hI2H29fBMj3kth4448Rpzdmd+f0o5aNYN7Fj9oQWBm44CBQFMzywLuAWoDuPuLwIfAICADyAWuCVYtIiJV3a69hTz04SLe/m417Zo2YMKNA+jVpklIPjtoQeDul5fxvAN/DNbni4hEigVrtvHHt//Lum17uPbEBG47uxP164TuhE1EDBaLiFRHe/KLeHTmYsZ+vZIWjWMY//sTSGp7ZMjrUBCIiITB3JVb+Ov4BazeksuVx8cz4uwuNK5XOyy1KAhEREJoe24BT/5nCW99u4oWjevx9g39GdC+aVhrUhCIiITIj2u28cd//5f12/dw5fHH8LfkLjSsG/5fw+GvQESkmttbWMRLn2Xy3KfLaB4bw6SbTqRniK4IKg8FgYhIEKVkbePOSQtJXbuD8xJbMGZID45oUCfcZf2CgkBEJAjyC4t5/tNlPD87gyMb1OHFK/uQ3KNqzqupIBARqWQZ2Tv58zs/krZuBxf3ac29g7sRGxOeK4LKQ0EgIlJJioudf369ksdmLqZB3Vq8eGVfknscHe6yyqQgEBGpBEs27GTUlFS+X7GFM7o05+GLjqV5o5hwl1UuCgIRkQrYtbeQpz5ayr++WUlsTC0evuhYhh7XBjMLd2nlpiAQETlM/0nfyOgpqWzYkcfl/eIZ8ZvOVe6KoPJQEIiIHKK12/YwZlo6M9M20PmoWJ6/og99jzki3GUdNgWBiMgh+CBlHXdOXEhBkTPi7M4MO6UdtYO8XkCwKQhERMph6+58Rk1J5YOU9fRs3ZjnLu8T1FXDQklBICJShtmLs/nb+yls3Z3Pbb/pxB9ObR/0VcNCSUEgInIAu/YW8uD0dMZ9v4bOR8Xyz6uPo0erxuEuq9IpCERE9uO7zM3cNmEBWVv38PtT2/HXszpRt1bNcJcVFAoCEZFS8gqKePKjJbz65QraHFGf8b8/gePCsGpYKCkIRERKLMzazl/H/8iy7F1c0T+euwZ1pUEVWC8g2Kr/EYqIlKG42HlhdgbPfLKMuIZ1GHvNcQzs3DzcZYWMgkBEotrabXu4dfyPfJu5hXMTW/DgBT1oUj/y7g6uCAWBiEQld2daynrumriQIncevfhYLkuKrDmCKouCQESiTvbOPEZNTmVW2kZ6tWnCs0N7V5ubww6HgkBEooa7M/nHtdw3LZ3c/CJGntOF609KqFY3hx0OBYGIRIV12/YwYsICvsrYTK82TXji0kQ6NI8Nd1lVgoJARKq9nyaKKyp2HrigB5f3i6dmjegbCzgQBYGIVFvrtu1hzAfpzEjdQM82TXh2aC+OiWsQ7rKqHAWBiFQ77s5b367i0ZlLKCgqrjbTRQeLgkBEqpUtu/O5c+JCZqZt4OSOTXnggh7qBZRBQSAi1cZnS3MY+X4Km3flM/KcLgw7uR01NBZQpqD2k8ws2cyWmFmGmY3cz/PxZjbbzOabWYqZDQpmPSJSPeUXFvP3/yzld69/T73aNXn/xgH84dT2CoFyClqPwMxqAi8AZwFZwA9mNtXd00s1uxsY7+7/MLNuwIdA22DVJCLVz/zVWxkxIYWM7F1c1KcVD114LDG1q+d00cESzFND/YAMd88EMLN3gCFA6SBwoFHJ48bAuiDWIyLVSFGx88oXmTw+awlHN4rhtd8lcUbXo8JdVkQKZhC0AtaU2s4C+u/T5l7gIzP7E9AAOHN/b2Rmw4BhAPHx8ZVeqIhEljVbcvnLuz8yb9VWzulxNI9ekkijmNrhLitihftaqsuBse7eGhgEvGlmv6rJ3V929yR3T2rWrFnIixSRqmN6ynrOffYLlm7cyd9/25P/+58+CoEKCmaPYC3QptR265J9pV0HJAO4+zdmFgM0BbKDWJeIRKD8wmIem7mYV79cQa82TXhGN4dVmmAGwQ9ARzNLIBAAQ4Er9mmzGjgDGGtmXYEYICeINYlIBFqwZhu3v5/C4g07ueqEY7j73G7UqRXuExrVR9CCwN0LzWw4MAuoCbzu7mlmdj8w192nArcCr5jZLQQGjq92dw9WTSISWXLzC/n7f5by2pcraB4bw6tXJXFmNw0IV7ag3lDm7h8SuCS09L7RpR6nAycGswYRiUzfLN/M7e+nsHpLLpf3i+eOQV00FhAkurNYRKqUXXsLeWTGIt76djXHxNXnnWHHc3y7uHCXVa0pCESkyvg4fSOjp6Syfkce152UwG2/6Uy9Oro5LNgUBCISdpt27eW+aelMW7COLkfH8twVvel7zJHhLitqKAhEJGzcnUnz1zLmg3R27y3i1rM68ftT2+uKoBBTEIhIWGTvyOOeqWnMSN1A7/gmPHZxIh2P0tKR4aAgEJGQcnem/LiOe6amsadkAXlNFx1eCgIRCZnsHXncOSmVjxdtpE98E564tCftmjUMd1lRT0EgIiExPWU9o6aksntvIXcN6sq1JyVoAfkqQkEgIkG1btse7puWxqy0jSS2bsyTl/bUWEAVoyAQkaBwd6YuWMeoyakUFDl/S+7MsJPbUUsLyFc5CgIRqXQbtucxekoqH6VvpHd8E57+rWYKrcoUBCJSaX66L+CeKWnkFxVzxzlduP7kdhoLqOIUBCJSKTbv2ssdExfyUXrgiqCnLutF26bqBUQCBYGIVNiHC9dz9+RUduUVcve5Xbn2xATdFxBBFAQictjyCop4cPoi3vx2FYmtG/PEpT3ppCuCIo6CQEQOy7xVWxkxYQGZObu54eQE/pbchdq6IigiKQhE5JDkFxbzzCdL+cec5bRoXI+3ruvPSR2bhrssqQAFgYiUW0b2Lv78znzS1u3g0r6tGX1+N2K1aljEUxCISJkKior519creXzWEurXqclL/9uXs7sfHe6ypJIoCETkoFKytvG3CSks3rCT07s055GLjqV5o5hwlyWVSEEgIvuVm1/I0x8v49UvMmkWW5cXr+zL2d2PwkyXhVY3CgIR+ZWUrG3c8u6PLM/ZzdDj2nDHoK40rqexgOpKQSAiPyssKub52Rk892kGzRrW5d/X9+fEDroiqLpTEIgIAEs37uT291OYv3obF/Zuxb2Du6sXECUUBCJRLr+wmOc+XcY/5iynYUwtnr28N4N7tgx3WRJCCgKRKLZq827+8u6PzF+9jYt6t+Kuc7sS17BuuMuSEFMQiEQhd+fdH9Zw/wfp1KphPH9Fb85LVC8gWikIRKLMhu15jJiwgC+WbWJA+zieuLQnLZvUC3dZEkYKApEo4e68Ny+LBz5Ip6DIGXNBD/6nX7ymixYFgUg0WLttD3dMXMjnS3Po1/ZIHrskUYvGyM+CGgRmlgw8A9QEXnX3R/bT5jLgXsCBBe5+RTBrEokm7s6479fw0IeLKHbn/iHdubL/MeoFyC8ELQjMrCbwAnAWkAX8YGZT3T29VJuOwB3Aie6+1cyaB6sekWizZksuIyem8FXGZga0j+PRixNpc2T9cJclVVAwewT9gAx3zwQws3eAIUB6qTY3AC+4+1YAd88OYj0iUaG42Hnru1U8MmMxNcx46MJjubxfG80RJAcUzCBoBawptZ0F9N+nTScAM/uKwOmje9195r5vZGbDgGEA8fHxQSlWpDpYtnEnd01O5fsVWzi5Y1MeuTiRVroiSMoQ7sHiWkBHYCDQGvjczI51922lG7n7y8DLAElJSR7iGkWqvPzCYp7+eCkvfZ5Jw7q1eOziRC5Naq1egJRLMINgLdCm1Hbrkn2lZQHfuXsBsMLMlhIIhh+CWJdItTJ7cTZjpqeTmbObS/u2ZuQ5XXR3sBySYAbBD0BHM0sgEABDgX2vCJoMXA7808yaEjhVlBnEmkSqjW25+YyeksbUBeto16wBr1+dxOldjgp3WRKBghYE7l5oZsOBWQTO/7/u7mlmdj8w192nljz3GzNLB4qAEe6+OVg1iVQXM1M3cPfkVLbl5vOXMzty48D21K1VM9xlSYQy98g65Z6UlORz584NdxkiYbE9t4B7p6Uxaf5aerRqxCMXJdKjVeNwlyURwMzmuXvS/p4L92CxiJTTjIXrGTUlja25+dx8Rkf+dHoHatesEe6ypBpQEIhUcdk78hg1JZVZaRvp3rIRY685Tr0AqVQKApEqyt0ZP3cND0xfRH5hMbcnd+GGkxOopV6AVDIFgUgVtHLTbu6ctJCvl2+mf8KRPHJxIgmaJE6CREEgUoXsLSzixTmZvDAng7o1a/DghT24/DhNFS3BpSAQqSK+ztjEqCmpLM/ZzXmJLRh9XjeaN4oJd1kSBRQEImGWvTOPh6YvYvKP62jVpB5jrzmOgZ01Ea+EjoJAJEyKip1Xv8jkmU+WUVBUzM2nd+Cm0zoQU1s3hkloKQhEwiBray63jl/Adyu2cFa3o7hzUFcNBkvYHDQIzKwGcLy7fx2iekSqtcKiYsZ+vZInP1pKDYMnLu3JxX1aaZZQCauDBoG7F5vZC0DvENUjUm2t2rybv7z7I/NXb+O0zs0Yc0EPWh+hFcMk/MpzaugTM7sYmOiRNjGRSBXg7rz7wxru/yCdWjWMZ4b2YnDPluoFSJVRniD4PfBXoMjM9gAGuLs3CmplItVAZs4uHpy+iE8WZzOgfRxPXNqTlloxTKqYMoPA3WNDUYhIdVJc7LzxzUoenrGYmjWMu8/tyrUnJujGMKmSynXVkJldBJwEOPCFu08OZlEikWzNllzumLiQLzM2cVrnZjx6caJuDJMqrcwgMLP/AzoA40p2/cHMznL3Pwa1MpEI4+5Mmr+We6akUVjsPHhhD67oF6+xAKnyytMjOB3o+tNAsZn9C0gLalUiEWbJhp2MnpLKdyu20Ce+Cc8M7U2bI3VFkESG8gRBBhAPrCrZblOyTyTqFRYV8+Jny3nmk2XUr1OLhy48lt8e14aaGguQCFKeIIgFFpnZ9wTGCPoBP5jZVAB3HxzE+kSqrIzsndw6fgELsrZzbmILxgzpwZEN6oS7LJFDVp4gqAecU2rbgEeBe4JSkUgVV1TsvPZlJk98tJQGdWry/BW9OS+xZbjLEjls5QmCWu7+WekdZlZv330i0SAzZxcjJqQwb9VWzup2FA9deCzNYuuGuyyRCjlgEJjZjcBNQDszSyn1VCzwVbALE6lK9uQX8fTHS3n9qxXUq12Tv/+2Jxf00hxBUj0crEfwNjADeBgYWWr/TnffEtSqRKqQrzM2ccekhazanMtlSa257ezONI/VfQFSfRwwCNx9O7AduDx05YhUHdtzC3jww3TGz82ibVx9xt1wPCe0jwt3WSKVTusRiOzD3ZmRuoHRU9LYmpvPH05tz1/O7KgFY6TaUhCIlLJ++x5GT0njP+kb6dGqEWOvOY4erRqHuyyRoFIQiAB5BUW89uUKnv80g2J37jinC9edlECtmjXCXZpI0CkIJOp9v2ILt773I2u27OHs7kdx97ndND2ERBUFgUStrbvzeWzWYsZ9v4bWR9Tj39f358QOTcNdlkjIKQgkKn2yaCMjJy5ky+58bjg5gVvO6kT9OvpxkOik//kSVXbmFTDmg8AloV2OjmXsNcfRvaUGgyW6BXUkzMySzWyJmWWY2ciDtLvYzNzMkoJZj0S3rzI2kfz0F0yYl8VNA9szZfiJCgERgtgjMLOawAvAWUAWJTOWunv6Pu1igT8D3wWrFoluufmFPDpjMf/6ZhXtmjZgwo0D6BN/RLjLEqkygnlqqB+Q4e6ZAGb2DjAESN+n3RgCs5mOCGItEqXmrdrCreMXsHJzLlcPaMvtyV2oV0c3homUFswgaAWsKbWdBfQv3cDM+gBt3H26mR0wCMxsGDAMID4+PgilSnWTV1DEkx8t4bUvV9CicT3evqE/A9rriiCR/QnbYLGZ1QCeAq4uq627vwy8DJCUlOTBrUwi3TfLN3PnpIWs2LSby/u14c5BXYmNqR3uskSqrGAGwVoCy1r+pHXJvp/EAj2AOSVT+R4NTDWzwe4+N4h1STW1LTefhz5cxPi5WcQfWZ+3ruvPSR3VCxApSzCD4Aego5klEAiAocAVPz1ZMrvpzz+lZjYHuE0hIIfK3Zm6YB1jPkhna24BNw5sz82nd9RYgEg5BS0I3L3QzIYDs4CawOvunmZm9wNz3X1qsD5bokdmzi7um5bOZ0tz6NmmCW9ceyzdWjYKd1kiESWoYwTu/iHw4T77Rh+g7cBg1iLVS2FRMS9+tpxnP8mgbq0a3HN+N646oS01a2jFMJFDpTuLJeIsWr+D299PISVrO+cmtuCe87tpxTCRClAQSMTYsjufJz9awrs/rKFJ/do8d3lvzu/ZMtxliUQ8BYFUee7O9IXrGT0ljR17Cri8Xzy3nNWJIxvUCXdpItWCgkCqtJydexk1OZWZaRtIbN2Yx284ns5Hx4a7LJFqRUEgVdJPl4TeMzWN3Pwibk/uwg0na8UwkWBQEEiVs3bbHh74IJ0ZqRvoHd+Exy9JpENz9QJEgkVBIFVGcbHz7+9W8ciMxRQWO39L7szvT2mvS0JFgkxBIFVCZs4uRr6/kO9XbuHkjk156MJjtW6wSIgoCCSsCoqKefnzTJ79ZBl1a9XgsUsSubRva0rmnxKREFAQSNh8nbGJUVNSWZ6zm3N6HM19g7vTvJFuDBMJNQWBhNzOvAIembGYf3+3mrZx9Xn1qiTO7HZUuMsSiVoKAgkZd2daynoe+CCd7J17ueHkBG79TWdiamuWUJFwUhBISGTvzOOeKWnMSN1Aj1aNePmqJHq1aRLuskQEBYEEWX5hMW98s5JnPl5GXmERI8/pwg0nt9MloSJViIJAgubzpTncOzWNzE27OaVTM+49vxvtmjUMd1kisg8FgVS67J15PPzhYibNX0tC0wa8fnUSp3VurktCRaooBYFUGndn8o9ruX9aOrv3FjH8tA4MP72DBoNFqjgFgVSK9dv3cMfEhcxZElgy8slLNT+QSKRQEEiF5BcW8/yny3jlixU4zr0lS0bW0GCwSMRQEMhhcXc+XZzNA9MXsWLTbgb3bMmIsztrfiCRCKQgkEO2Zksud01O5fOlObRr1oCx1xzHwM7Nw12WiBwmBYGU297CIl79YgXPfbqMWjVqMOq8blx1wjHU1mIxIhFNQSDl8lnJPQErNu0mufvR3H1eV1ofodNAItWBgkAOatXm3dw7NY3ZS3Jo17QBb1zbj1M6NQt3WSJSiRQEsl95BUW89FkmL8zJoHYN445zunD1iW2pW0v3BIhUNwoC+ZXPl+ZwT8lpoHMTWzDq3G4c3VjrBIhUVwoC+dmG7XmMmZ7O9JT1HBNXX6eBRKKEgkAoKCpm7FcrefrjpRQWO385syM3Dmyv00AiUUJBEOW+WJbD6CmB00BndGnO6PO7cUxcg3CXJSIhpCCIUtk783jgg0VMXbCOhKYNeOWqJM7sqhlCRaJRUIPAzJKBZ4CawKvu/sg+z/8VuB4oBHKAa919VTBrinbFxc7b36/m0ZmL2VtQzJ/PCJwG0gyhItEraEFgZjWBF4CzgCzgBzOb6u7ppZrNB5LcPdfMbgQeA34brJqi3ZINOxk5MYX5q7cxoH0cYy7oQXstFCMS9YLZI+gHZLh7JoCZvQMMAX4OAnefXar9t8CVQawnahUUFfPy55k88/EyGsbU4qnLenJh71Y6DSQiQHCDoBWwptR2FtD/IO2vA2bs7wkzGwYMA4iPj6+s+qLCgjXbuP39FBZv2Ely96N58MIexDWsG+6yRKQKqRKDxWZ2JZAEnLq/5939ZeBlgKSkJA9haRErN7+QJz9ayj+/WkGz2Lq89L99Obv70eEuS0SqoGAGwVqgTant1iX7fsHMzgTuAk51971BrCdqzFmSzd2TU8nauocrj4/nb8ldaBRTO9xliUgVFcwg+AHoaGYJBAJgKHBF6QZm1ht4CUh29+wg1hIV1m/fw31T05mZtoH2zRrw3h9O4Li2R4a7LBGp4oIWBO5eaGbDgVkELh993d3TzOx+YK67TwUeBxoC75UMXK5298HBqqm6Kip2/vX1Sh6ftYQid0ac3ZnrT07QncEiUi5BHSNw9w+BD/fZN7rU4zOD+fnRYMGabdw9OZWFa7dzWudm3D+kh5aLFJFDUiUGi+XQ7dpbyDMfL+XVL1fQrGFdnhnai8E9W+qSUBE5ZAqCCFNc7Eycv5ZHZy5m0669DD2uDXcO6kqsBoNF5DApCCLI/NVbuf+DdOav3kbv+Ca8clUSvdo0CXdZIhLhFAQRYOvufMZMT2fif9fSLLYuT14auDO4Rg2dBhKRilMQVHGfLt7I3yYsZPuefP5wanuGn96BhnX1bRORyqPfKFVU6V5Al6NjeePafnRr2SjcZYlINaQgqGKKSqaJfmLWEnbvLeSPp7Xn5jM66p4AEQkaBUEVkrp2O3dNWsiCrO0MaB/H6PO70eVo9QJEJLgUBFXAjrwCnvpoKW98s5IjG+ieABEJLQVBGLk701LWM+aDdDbt2stVxx/DX3/Tmcb1dE+AiISOgiBMMnN2MXpKGl9mbOLYVo157XdJJLZuEu6yRCQKKQhCLK+giP+bncGLn2VSt3YNxgzpzhX9j6Gm7gkQkTBREITQnCXZ3DM1jVWbc7mgV0vuPLcrzWNjwl2WiEQ5BUEIbNyRx/3T0pm+cD3tmjXg7ev7M6BD03CXJSICKAiCqrjYeeOblTz50VLyi4q57TeduOGUdronQESqFAVBkHy+NIdHZiwmff0OTu7YlPuH9CChaYNwlyUi8isKgkq2Zksu93+Qzn/SN9LmyHo8e3lvzk9soXsCRKTKUhBUkryCIv4xZzkvfracmjWM25O7cO1JbXUaSESqPAVBJfhk0UbunZbGmi17OC+xBXed25UWjeuFuywRkXJREFRA9o487iu5GqhD84a8fUN/BrTX1UAiElkUBIdpZup6Rk5cyJ78Im49qxN/GNie2jVrhLssEZFDpiA4RDvzCnhs5hLe/HYVPVs35qnf9qJ9s4bhLkukSiooKCArK4u8vLxwlxI1YmJiaN26NbVrl3/OMgVBOf20aPwjMwKLxl93UgK3J3ehTi31AkQOJCsri9jYWNq2basr50LA3dm8eTNZWVkkJCSU+3UKgnL4LnMzD0xfxMK12+kd34TXfpdETy0aL1KmvLw8hUAImRlxcXHk5OQc0usUBAexI6+AMdPSeW9eFq2a1OPxSxK5uE9rLRovcggUAqF1OF9vBcEBfJCyjvumpbNldz43DmzPn07vQP06+nKJSPWjE9z72LA9jz+Nm8/wt+fTsnEMk24awO3JXRQCIhFs8uTJmBmLFy/+ed+cOXM477zzftHu6quvZsKECUBgoHvkyJF07NiRPn36cMIJJzBjxowK1/Lwww/ToUMHOnfuzKxZsw7a9uabb6Zhw/9/McqqVas444wzSExMZODAgWRlZVW4HlAQ/CyvoIjnPlnG6U/OYVbqBv5yZkcm3DhAi8WIVAPjxo3jpJNOYty4ceV+zahRo1i/fj2pqan897//ZfLkyezcubNCdaSnp/POO++QlpbGzJkzuemmmygqKtpv27lz57J169Zf7Lvtttu46qqrSElJYfTo0dxxxx0Vqucn+jMX+ChtA/dNS2fttj0kdz+aOwd1JT6ufrjLEqlW7puWRvq6HZX6nt1aNuKe87sftM2uXbv48ssvmT17Nueffz733Xdfme+bm5vLK6+8wooVK6hbty4ARx11FJdddlmF6p0yZQpDhw6lbt26JCQk0KFDB77//ntOOOGEX7QrKipixIgRvP3220yaNOnn/enp6Tz11FMAnHbaaVxwwQUVqucnUd0j2Lgjj+v/9QPD3pxHbEwt3ryuHy/+b1+FgEg1MmXKFJKTk+nUqRNxcXHMmzevzNdkZGQQHx9Po0aNymx7yy230KtXr1/9e+SRR37Vdu3atbRp0+bn7datW7N27dpftXv++ecZPHgwLVq0+MX+nj17MnHiRAAmTZrEzp072bx5c5k1liUqewTZO/L493eref2rFRQWOSPP6cK1JybongCRICrrL/dgGTduHH/+858BGDp0KOPGjaNv374HvLrmUK+6+fvf/17hGktbt24d7733HnPmzPnVc0888QTDhw9n7NixnHLKKbRq1YqaNSs+sWVQg8DMkoFngJrAq+7+yD7P1wXeAPoCm4HfuvvKYNb0VcYm/vDWPHbmFXJ6l+bcdW5X3RksUk1t2bKFTz/9lIULF2JmFBUVYWY8/vjjxMXF/eoc/JYtW2jatCkdOnRg9erV7Nixo8xewS233MLs2bN/tX/o0KGMHDnyF/tatWrFmjVrft7OysqiVatWv2gzf/58MjIy6NChAxA4TdWhQwcyMjJo2bLlzz2CXbt28f7779OkSZNyfz0OyN2D8o/AL//lQDugDrAA6LZPm5uAF0seDwXeLet9+/bt64dr2oK13v6O6X7mk3M8I3vnYb+PiJRPenp6WD//pZde8mHDhv1i3ymnnOKfffaZ5+Xledu2bX+uceXKlR4fH+/btm1zd/cRI0b41Vdf7Xv37nV39+zsbB8/fnyF6klNTfXExETPy8vzzMxMT0hI8MLCwoO+pkGDBj8/zsnJ8aKiInd3v/POO33UqFH7fc3+vu7AXD/A79VgngvpB2S4e6a75wPvAEP2aTME+FfJ4wnAGRaku0+m/LiWP7/zI73jmzDxpgHqBYhEgXHjxnHhhRf+Yt/FF1/MuHHjqFu3Lm+99RbXXHMNvXr14pJLLuHVV1+lcePGADzwwAM0a9aMbt260aNHD84777xyjRkcTPfu3bnsssvo1q0bycnJvPDCCz+f2hk0aBDr1q076OvnzJlD586d6dSpExs3buSuu+6qUD0/sUBQVD4zuwRIdvfrS7b/F+jv7sNLtUktaZNVsr28pM2mfd5rGDAMID4+vu+qVasOuZ5vMzfz6hcreHpoLxrWjcqhEZGQW7RoEV27dg13GVFnf193M5vn7kn7ax8RvxHd/WXgZYCkpKTDSq7j28VxfLu4Sq1LRKQ6COapobVAm1LbrUv27beNmdUCGhMYNBYRkRAJZhD8AHQ0swQzq0NgMHjqPm2mAr8reXwJ8KkH61yViISFfqRD63C+3kELAncvBIYDs4BFwHh3TzOz+81scEmz14A4M8sA/gqM3P+7iUgkiomJYfPmzQqDEPGS9QhiYmIO6XVBGywOlqSkJJ87d264yxCRctAKZaF3oBXKIn6wWEQiU+3atQ9ppSwJD82pICIS5RQEIiJRTkEgIhLlIm6w2MxygEO/tTigKbCpzFbVi445OuiYo0NFjvkYd2+2vyciLggqwszmHmjUvLrSMUcHHXN0CNYx69SQiEiUUxCIiES5aAuCl8NdQBjomKODjjk6BOWYo2qMQEREfi3aegQiIrIPBYGISJSrlkFgZslmtsTMMszsVzOamlldM3u35PnvzKxtGMqsVOU45r+aWbqZpZjZJ2Z2TDjqrExlHXOpdhebmZtZxF9qWJ5jNrPLSr7XaWb2dqhrrGzl+L8db2azzWx+yf/vQeGos7KY2etmll2yguP+njcze7bk65FiZn0q/KEHWsw4Uv8BNYHlQDugDrAA6LZPm5uAF0seDwXeDXfdITjm04D6JY9vjIZjLmkXC3wOfAskhbvuEHyfOwLzgSNKtpuHu+4QHPPLwI0lj7sBK8NddwWP+RSgD5B6gOcHATMAA44HvqvoZ1bHHkE/IMPdM909H3gHGLJPmyHAv0oeTwDOMDMLYY2VrcxjdvfZ7p5bsvktgRXjIll5vs8AY4BHgeowD3J5jvkG4AV33wrg7tkhrrGyleeYHfhpVfnGwMFXgK/i3P1zYMtBmgwB3vCAb4EmZtaiIp9ZHYOgFbCm1HZWyb79tvHAAjrbgUhe0Lg8x1zadQT+oohkZR5zSZe5jbtPD2VhQVSe73MnoJOZfWVm35pZcsiqC47yHPO9wJVmlgV8CPwpNKWFzaH+vJdJ6xFEGTO7EkgCTg13LcFkZjWAp4Crw1xKqNUicHpoIIFe3+dmdqy7bwtnUUF2OTDW3Z80sxOAN82sh7sXh7uwSFEdewRrgTaltluX7NtvGzOrRaA7uTkk1QVHeY4ZMzsTuAsY7O57Q1RbsJR1zLFAD2COma0kcC51aoQPGJfn+5wFTHX3AndfASwlEAyRqjzHfB0wHsDdvwFiCEzOVl2V6+f9UFTHIPgB6GhmCWZWh8Bg8NR92kwFflfy+BLgUy8ZhYlQZR6zmfUGXiIQApF+3hjKOGZ33+7uTd29rbu3JTAuMtjdI3md0/L8355MoDeAmTUlcKooM4Q1VrbyHPNq4AwAM+tKIAhyQlplaE0Friq5euh4YLu7r6/IG1a7U0PuXmhmw4FZBK44eN3d08zsfmCuu08FXiPQfcwgMCgzNHwVV1w5j/lxoCHwXsm4+Gp3Hxy2oiuonMdcrZTzmGcBvzGzdKAIGOHuEdvbLecx3wq8Yma3EBg4vjqS/7Azs3EEwrxpybjHPUBtAHd/kcA4yCAgA8gFrqnwZ0bw10tERCpBdTw1JCIih0BBICIS5RQEIiJRTkEgIhLlFAQiIlFOQSByGMzsZjNbZGb/DnctIhWly0dFDoOZLQbOdPescrStVTKnlUiVpB6ByCEysxcJTIs8w8y2m9mbZvaNmS0zsxtK2gw0sy/MbCqQHtaCRcqgHoHIYSiZvygJGA5cSGAuowYE1gLoT2Bqh+lAj5I5f0SqLPUIRCpuirvvcfdNwGwCc+gDfK8QkEigIBCpuH271T9t7w51ISKHQ0EgUnFDzCzGzOIITBb2Q5jrETkkCgKRikshcEroW2CMu0f0UokSfTRYLFIBZnYvsMvdnwh3LSKHSz0CEZEopx6BiEiUU49ARCTKKQhERKKcgkBEJMopCEREopyCQEQkyv0/SIXq/VA47i4AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEWCAYAAABrDZDcAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAYXElEQVR4nO3dfZQddZ3n8ffXJBgQhEwSHU0nJpDAEgWD9BJ8QNmVwcAsiWcGTdhFYYYhKxoH8WFwj4wGRnd1QGdGxVFWUHAkCMwI7eHJw4OirmjCgjwE42lDkA6MJFFYMUCevvvHreDtTqe7Ot11L931fp3Th1u/+t263+ru8Omq+tWvIjORJNXXi9pdgCSpvQwCSao5g0CSas4gkKSaMwgkqeYMAkmqOYNAkmrOIJCGKCLWRcQzEfF0RPw6Ir4eEftGxPci4tmifWNE/FtEvKLd9UqDMQikPXNSZu4LvA7oBM4r2pcV7bOBfYGL2lSfVJpBIA1DZq4HbgJe06f9SeA6YF7Li5KGyCCQhiEipgMnAvf0aZ8M/BnQ3Y66pKEI5xqShiYi1gFTgG3AU8ANwIdoHBkcBWwFXgr8DFiYmb9qT6VSOR4RSHvm7Zl5QGa+KjPfm5nPFO1/nZn7A4cDk4CO9pUolWMQSBXIzPuBTwIXR0S0ux5pIAaBVJ3LgZcDC9tdiDQQg0CqSGZuAf4J+Nt21yINxIvFklRzHhFIUs0ZBJJUcwaBJNWcQSBJNTe+3QUM1ZQpU3LmzJntLkOSRpW77757Y2ZO7W/dqAuCmTNnsmrVqnaXIUmjSkQ8srt1nhqSpJozCCSp5gwCSao5g0CSas4gkKSaqywIIuKyiHgiIh7YzfqIiM9HRHdE3BcRr6uqFknS7lV5RPB1YMEA608A5hRfS4F/rrAWSdJuVBYEmXkn8JsBuiwCrsiGu4ADIuIVVdVz8wP/zvH/8H22bNtR1UdI0qjUzmsE04BHm5Z7irZdRMTSiFgVEas2bNiwRx/2nn+5m1/8+mk2Pv3cHr1fksaqUXGxODMvyczOzOycOrXfO6RL277D5y9IUrN2BsF6YHrTckfRJklqoXYGQRfw7mL00NHAU5n5eBvrkaRaqmzSuYhYARwLTImIHuATwASAzPwycCNwItANbAb+oqpaJEm7V1kQZOYpg6xP4H1Vfb4kqZxRcbFYklSd2gVBOmhIknqpXRBIknozCCSp5gwCSao5g0CSas4gkKSaMwgkqeZqFwSJ40clqVntgkCS1JtBIEk1ZxBIUs0ZBJJUcwaBJNWcQSBJNWcQSFLN1S4InIZaknqrXRBIknozCCSp5gwCSao5g0CSas4gkKSaMwgkqeZqFwSOHpWk3moXBJKk3gwCSao5g0CSas4gkKSaMwgkqeYMAkmqudoFQTr9qCT1UmkQRMSCiFgTEd0R8dF+1s+IiDsi4p6IuC8iTqyyHknSrioLgogYB1wMnADMBU6JiLl9up0HXJ2ZRwBLgC9VVY8kqX9VHhEcBXRn5trM3AJcBSzq0yeBlxav9wceq7AeSVI/qgyCacCjTcs9RVuz5cCpEdED3Ai8v78NRcTSiFgVEas2bNhQRa2SVFvtvlh8CvD1zOwATgS+ERG71JSZl2RmZ2Z2Tp06teVFStJYVmUQrAemNy13FG3NzgCuBsjMHwMTgSkV1iRJ6qPKIFgJzImIWRGxF42LwV19+vwKeCtARBxKIwgqPffj4FFJ6q2yIMjMbcAy4BbgIRqjgx6MiAsiYmHR7UPAmRHxM2AFcHo60F+SWmp8lRvPzBtpXARubvt40+vVwBurrEGSNLB2XyyWJLWZQSBJNWcQSFLNGQSSVHMGgSTVXO2CwMGpktRb7YJAktSbQSBJNWcQSFLNGQSSVHMGgSTVnEEgSTVXwyBw/KgkNathEEiSmhkEklRzBoEk1ZxBIEk1ZxBIUs0ZBJJUc7ULAmcflaTeahcEkqTeDAJJqjmDQJJqziCQpJozCCSp5gwCSaq52gWBo0clqbfaBYEkqTeDQJJqziCQpJqrNAgiYkFErImI7oj46G76vDMiVkfEgxFxZZX1SJJ2Nb6qDUfEOOBi4E+AHmBlRHRl5uqmPnOA/wG8MTN/GxEvq6oeSVL/qjwiOArozsy1mbkFuApY1KfPmcDFmflbgMx8osJ6JEn9KH1EEBHTgFc1vycz7xzgLdOAR5uWe4D5ffocXGz7R8A4YHlm3tzPZy8FlgLMmDGjbMmSpBJKBUFEfAZYDKwGthfNCQwUBGU/fw5wLNAB3BkRh2Xmk82dMvMS4BKAzs7OYd0K4DTUktRb2SOCtwOHZOZzQ9j2emB603JH0dasB/hJZm4FHo6IX9AIhpVD+BxJ0jCUvUawFpgwxG2vBOZExKyI2AtYAnT16XMdjaMBImIKjVNFa4f4OZKkYSh7RLAZuDcibgOePyrIzL/e3Rsyc1tELANuoXH+/7LMfDAiLgBWZWZXse74iNh5yukjmblpD/dFkrQHygZBF7v+NT+ozLwRuLFP28ebXifwweJLktQGpYIgMy8vTu8cXDStKc7rS5JGubKjho4FLgfWAQFMj4jTBhk+KkkaBcqeGvoscHxmrgGIiIOBFcCRVRVWlXQiaknqpeyooQk7QwAgM3/B0EcRSZJegMoeEayKiK8C/1Is/zdgVTUlSZJaqWwQnAW8D9g5XPQHwJcqqUiS1FJlRw09B3yu+JIkjSEDBkFEXJ2Z74yI++nncb+ZeXhllUmSWmKwI4Kzi//+l6oLkSS1x4CjhjLz8eLlRuDRzHwEeDHwWuCximurhLOPSlJvZYeP3glMLJ5J8F3gXcDXqypKktQ6ZYMgMnMz8GfAlzLzHcCrqytLktQqpYMgIl5P4/6BG4q2cdWUJElqpbJB8AEaD5n/djGV9IHAHZVVJUlqmbL3EXwf+H7T8lr+cHOZJGkUG+w+gn/MzA9ExHfo/z6ChZVVJklqicGOCL5R/PeiqgtpFYePSlJvAwZBZt5dvFwFPJOZOwAiYhyN+wkkSaNc2YvFtwH7NC3vDdw68uVIklqtbBBMzMyndy4Ur/cZoL8kaZQoGwS/j4jX7VyIiCOBZ6opSZLUSmWfR/AB4JqIeIzGM4v/GFhcVVGSpNYpex/Byoj4D8AhRdOazNxaXVmSpFYpdWooIvYBzgXOzswHgJkR4dTUkjQGlL1G8DVgC/D6Ynk98MlKKqpY7npfnCTVWtkgOCgz/x7YClDMRBqVVSVJapmyQbAlIvammGYiIg4CnqusKklSy5QdNfQJ4GZgekR8E3gjcHpVRUmSWmfQIIiIFwGTaDyU5mgap4TOzsyNFdcmSWqBQYMgM3dExN9k5tX84aE0kqQxouw1glsj4sMRMT0i/mjnV6WVSZJaomwQLAbeS+PhNKuavgYUEQsiYk1EdEfERwfo9+cRkRHRWbKePeY01JLUW9kgmAtcDPwMuBf4AoM8vL6Yqvpi4ITi/adExNx++u0HnA38pHTVkqQRUzYILgcOBT5PIwTmFm0DOQrozsy1mbkFuApY1E+/vwM+AzxbshZJ0ggqO3z0NZnZ/Nf8HRGxepD3TAMebVruAeY3dyhmNJ2emTdExEd2t6GIWAosBZgxY0bJkiVJZZQ9Ivi/EXH0zoWImE+JawQDKYalfg740GB9M/OSzOzMzM6pU6cO52MlSX2UPSI4Evg/EfGrYnkGsCYi7gcyMw/v5z3rgelNyx1F2077Aa8BvhcR0JjauisiFmbmsEJGklRe2SBYsAfbXgnMiYhZNAJgCfBfd67MzKeAKTuXI+J7wIcNAUlqrbLPI3hkqBvOzG0RsQy4BRgHXJaZD0bEBcCqzOwa6jYlSSOv7BHBHsnMG4Eb+7R9fDd9j62yFklS/8peLJYkjVEGgSTVnEEgSTVnEEhSzRkEklRztQsCZx+VpN5qFwSSpN4MAkmqOYNAkmrOIJCkmjMIJKnmDAJJqjmDQJJqrnZBkHgjgSQ1q10QSJJ6MwgkqeYMAkmqOYNAkmrOIJCkmjMIJKnmahcETkMtSb3VLggkSb0ZBJJUcwaBJNWcQSBJNWcQSFLNGQSSVHO1CwJHj0pSb7ULAklSbwaBJNVcpUEQEQsiYk1EdEfER/tZ/8GIWB0R90XEbRHxqirrkSTtqrIgiIhxwMXACcBc4JSImNun2z1AZ2YeDlwL/H1V9UiS+lflEcFRQHdmrs3MLcBVwKLmDpl5R2ZuLhbvAjoqrEeS1I8qg2Aa8GjTck/RtjtnADf1tyIilkbEqohYtWHDhhEsUZL0grhYHBGnAp3Ahf2tz8xLMrMzMzunTp06rM9Kpx+VpF7GV7jt9cD0puWOoq2XiDgO+Bjwlsx8rsJ6JEn9qPKIYCUwJyJmRcRewBKgq7lDRBwBfAVYmJlPVFiLJGk3KguCzNwGLANuAR4Crs7MByPigohYWHS7ENgXuCYi7o2Irt1sTpJUkSpPDZGZNwI39mn7eNPr46r8fEnS4F4QF4slSe1jEEhSzRkEklRztQsC7yKQpN5qFwSSpN4MAkmqOYNAkmrOIJCkmjMIJKnmDAJJqrnaBYGzUEtSb7ULAklSbwaBJNWcQSBJNWcQSFLNGQSSVHMGgSTVXA2DwPGjktSshkEgSWpmEEhSzRkEklRz49tdgKT62rp1Kz09PTz77LPtLmXMmDhxIh0dHUyYMKH0ewwCSW3T09PDfvvtx8yZM4mIdpcz6mUmmzZtoqenh1mzZpV+n6eGJLXNs88+y+TJkw2BERIRTJ48echHWAaBpLYyBEbWnnw/axcETkMtSb3VLggkqa/rrruOiODnP//5823r1q1j7733Zt68ecydO5f3vOc97NixY1if89xzz7F48WJmz57N/PnzWbduXb/9br75Zg455BBmz57Npz/96efbH374YebPn8/s2bNZvHgxW7ZsGVY9OxkEkmpvxYoVvOlNb2LFihW92g866CDuvfde7rvvPlavXs111103rM+59NJLmTRpEt3d3Zxzzjmce+65u/TZvn0773vf+7jppptYvXo1K1asYPXq1QCce+65nHPOOXR3dzNp0iQuvfTSYdWzk6OGJL0gnP+dB1n92P8b0W3OfeVL+cRJrx6wz9NPP80Pf/hD7rjjDk466STOP//8XfqMHz+eN7zhDXR3dw+rnuuvv57ly5cDcPLJJ7Ns2TIys9d5/Z/+9KfMnj2bAw88EIAlS5Zw/fXXc+ihh3L77bdz5ZVXAnDaaaexfPlyzjrrrGHVBB4RSKq566+/ngULFnDwwQczefJk7r777l36bN68mdtuu43DDjtsl3XHHHMM8+bN2+Xr1ltv3aXv+vXrmT59OtAIl/33359Nmzbttg9AR0cH69evZ9OmTRxwwAGMHz++V/tI8IhA0gvCYH+5V2XFihWcffbZQOOv7xUrVnDkkUcC8Mtf/pJ58+YRESxatIgTTjhhl/f/4Ac/aGm9Vag0CCJiAfBPwDjgq5n56T7rXwxcARwJbAIWZ+a6Kmv62o/WMXHCOCa9ZC9euf9Eh65JNfab3/yG22+/nfvvv5+IYPv27UQEF154IfCHawQDOeaYY/jd7363S/tFF13Ecccd16tt2rRpPProo3R0dLBt2zaeeuopJk+e3G+fnXp6epg2bRqTJ0/mySefZNu2bYwfP/759pFQWRBExDjgYuBPgB5gZUR0Zebqpm5nAL/NzNkRsQT4DLC4qpoAbrj/cW64//F+171kr3G88oC9eezJZzhixqRe6wbLi76B0l/3vtvo26e/UNq1z8A9+quzbNSVzcQYZItZ0VTfVQz9rWo0cXXDlEd+w1XVWmazf/nqCazb+PsR325ZK674Jm9/xxI+9dkvPN+2ZOHbuPo73+WVHdPZun0HDw9S3xXfvnm36/q+9w3/+W184Stf5Y/nHM53vn0N89/4ZtZt2tyrz5RZc3lozS+48+4HefkrXskV37ySf/zyZazbtJk3vfktXHvttSxZsoTLL7+cRYsW7cFe76rKI4KjgO7MXAsQEVcBi4DmIFgELC9eXwt8MSIic+R/NQ/YZwJPbt7aq+3AKS9h4oRxrH68cYFq6n4vZu3G3/Pajv15Zuv25/v1LadvcX2r7bf4IW6j0ScH7FPmc0f6W1l2c6PpQKuqo8KqvgVVlFvVz2uwPxq27xjP1u17MCRzhOrt+tdrOPP9H2BbMSw0gOP/dCHX/9s1LF32ATJh+7CGjPYu9ORT3s2Hl53Jsf/xcA44YBL/8JWvsX1H8ut/f5yPfXAZX73yX4kXjePj//MiTnvnIrZv38HJp7yLgw4+lO07kvM/+SnOPP3dnHfeeRxxxBGcccYZw6itqcoK/p/b2HDEycCCzPyrYvldwPzMXNbU54GiT0+x/Muiz8Y+21oKLAWYMWPGkY888siQ6/nemid4/5X3cP/5b9vTXZI0wh566CEOPfTQdpcx5vT3fY2IuzOzs7/+o2LUUGZekpmdmdk5derUPdrGsYe8zBCQpH5UGQTrgelNyx1FW799ImI8sD+Ni8aSpBapMghWAnMiYlZE7AUsAbr69OkCTitenwzcXsX1AUkvXP6TH1l78v2sLAgycxuwDLgFeAi4OjMfjIgLImJh0e1SYHJEdAMfBD5aVT2SXngmTpzIpk2bDIMRsvN5BBMnThzS+yq7WFyVzs7OXLVqVbvLkDQCfELZyNvdE8oGuljsncWS2mbChAlDepKWqjEqRg1JkqpjEEhSzRkEklRzo+5icURsAIZ+a3HDFGDjoL3GFve5HtznehjOPr8qM/u9I3fUBcFwRMSq3V01H6vc53pwn+uhqn321JAk1ZxBIEk1V7cguKTdBbSB+1wP7nM9VLLPtbpGIEnaVd2OCCRJfRgEklRzYzIIImJBRKyJiO6I2GVG04h4cUR8q1j/k4iY2YYyR1SJff5gRKyOiPsi4raIeFU76hxJg+1zU78/j4iMiFE/1LDMPkfEO4uf9YMRcWWraxxpJX63Z0TEHRFxT/H7fWI76hwpEXFZRDxRPMGxv/UREZ8vvh/3RcTrhv2hmTmmvoBxwC+BA4G9gJ8Bc/v0eS/w5eL1EuBb7a67Bfv8n4B9itdn1WGfi377AXcCdwGd7a67BT/nOcA9wKRi+WXtrrsF+3wJcFbxei6wrt11D3Of3wy8DnhgN+tPBG6i8UDko4GfDPczx+IRwVFAd2auzcwtwFXAoj59FgGXF6+vBd4aVT3BvDUG3efMvCMzNxeLd9F4YtxoVubnDPB3wGeAsTDPcZl9PhO4ODN/C5CZT7S4xpFWZp8TeGnxen/gsRbWN+Iy807gNwN0WQRckQ13AQdExCuG85ljMQimAY82LfcUbf32ycYDdJ4CJrekumqU2edmZ9D4i2I0G3Sfi0Pm6Zl5QysLq1CZn/PBwMER8aOIuCsiFrSsumqU2eflwKkR0QPcCLy/NaW1zVD/vQ/K5xHUTEScCnQCb2l3LVWKiBcBnwNOb3MprTaexumhY2kc9d0ZEYdl5pPtLKpipwBfz8zPRsTrgW9ExGsyc0e7CxstxuIRwXpgetNyR9HWb5+IGE/jcHJTS6qrRpl9JiKOAz4GLMzM51pUW1UG2+f9gNcA34uIdTTOpXaN8gvGZX7OPUBXZm7NzIeBX9AIhtGqzD6fAVwNkJk/BibSmJxtrCr1730oxmIQrATmRMSsiNiLxsXgrj59uoDTitcnA7dncRVmlBp0nyPiCOArNEJgtJ83hkH2OTOfyswpmTkzM2fSuC6yMDNH83NOy/xuX0fjaICImELjVNHaFtY40srs86+AtwJExKE0gmBDS6tsrS7g3cXooaOBpzLz8eFscMydGsrMbRGxDLiFxoiDyzLzwYi4AFiVmV3ApTQOH7tpXJRZ0r6Kh6/kPl8I7AtcU1wX/1VmLmxb0cNUcp/HlJL7fAtwfESsBrYDH8nMUXu0W3KfPwT874g4h8aF49NH8x92EbGCRphPKa57fAKYAJCZX6ZxHeREoBvYDPzFsD9zFH+/JEkjYCyeGpIkDYFBIEk1ZxBIUs0ZBJJUcwaBJNWcQSC1UEScHhFfLF4vj4gPt7smySCQSihu3vHfi8Ykf7Gl3YiImcU8+FcADwB/GxErizngz2/q9+6i7WcR8Y2i7aTiWRf3RMStEfHydu2HNJgxd2exNMLm0JiO5KU0piM5isY88F0R8WYac1SdB7whMzdGxB8V7/shcHRmZkT8FfA3NO6AlV5wDAJpYI9k5l0RcRFwPI2HvkBjuo45wGuBazJzI0Bm7pxHvgP4VjFP/F7Aw60tWyrPU0PSwH5f/DeA/5WZ84qv2Zl56QDv+wLwxcw8DPjvNCZCk16QDAKpnFuAv4yIfQEiYlpEvAy4HXhHREwu2neeGtqfP0wNfFrfjUkvJJ4akkrIzO8WUxz/uJi99Wng1GImzE8B34+I7TROHZ1O46lZ10TEb2mExay2FC6V4OyjklRznhqSpJozCCSp5gwCSao5g0CSas4gkKSaMwgkqeYMAkmquf8P4Fgg1yv2Z9UAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#PR and ROC Curves\n",
    "\n",
    "from sklearn.metrics import roc_curve, precision_recall_curve, auc\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "last_pred = pred_list[len(pred_list)-1][len(pred_list[0])-1].clone()\n",
    "#last_pred = pred_list[len(pred_list)-2].clone()\n",
    "y_torch_test_0 = y_torch_test[:, 0]\n",
    "\n",
    "fpr, tpr, thresholds = roc_curve(y_torch_test_0.flatten(), last_pred.flatten())\n",
    "roc_auc = auc(fpr, tpr)\n",
    "\n",
    "precision, recall, thresholds = precision_recall_curve(y_torch_test_0.flatten(), last_pred.flatten())\n",
    "\n",
    "#printing optimal ROC threshold\n",
    "optimal_thresh = thresholds[np.argmax(tpr - fpr)]\n",
    "print(\"Optimal Threshold: \", optimal_thresh)\n",
    "\n",
    "#plotting\n",
    "plt.figure()\n",
    "plt.title(\"ROC\")\n",
    "plt.xlabel(\"fpr\")\n",
    "plt.ylabel(\"tpr\")\n",
    "plt.plot(fpr, tpr, label = 'AUC = %0.2f' % roc_auc)\n",
    "plt.legend(loc = 'lower right')\n",
    "\n",
    "plt.figure()\n",
    "plt.title(\"PR\")\n",
    "plt.xlabel(\"recall\")\n",
    "plt.ylabel(\"precision\")\n",
    "plt.plot(recall, precision, label = \"AP = %0.2f\" % np.mean(precision))\n",
    "plt.legend(loc = 'lower right')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "1d7d1464",
   "metadata": {},
   "outputs": [],
   "source": [
    "#thresholding for test image 0\n",
    "\n",
    "#pred2 = pred_list[len(pred_list)-2].clone().detach()\n",
    "\n",
    "#pred2 = pred.clone().detach()\n",
    "#pred2_0 = pred2[:,0]\n",
    "\n",
    "pred2_0 = last_pred[:,0]\n",
    "\n",
    "predN0 = pred2_0.numpy()\n",
    "#for i in range(predN.shape[0]):\n",
    "for i in range(1):\n",
    "    for a in range(330):\n",
    "        for b in range(330):\n",
    "            for c in range(100):\n",
    "                if predN0[i][a][b][c]  > optimal_thresh:\n",
    "                    predN0[i][a][b][c] = 1\n",
    "                else:\n",
    "                    predN0[i][a][b][c] = 0\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "16bfc7cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/shrey2/opt/anaconda3/envs/nd/lib/python3.9/site-packages/napari/_qt/qt_event_loop.py:256: FutureWarning: \n",
      "The 'gui_qt()' context manager is deprecated.\n",
      "If you are running napari from a script, please use 'napari.run()' as follows:\n",
      "\n",
      "    import napari\n",
      "\n",
      "    viewer = napari.Viewer()  # no prior setup needed\n",
      "    # other code using the viewer...\n",
      "    napari.run()\n",
      "\n",
      "In IPython or Jupyter, 'napari.run()' is not necessary. napari will automatically\n",
      "start an interactive event loop for you: \n",
      "\n",
      "    import napari\n",
      "    viewer = napari.Viewer()  # that's it!\n",
      "\n",
      "  warn(\n"
     ]
    }
   ],
   "source": [
    "import napari\n",
    "with napari.gui_qt():\n",
    "    viewer = napari.Viewer(ndisplay=3)\n",
    "    viewer.add_image((x_torch_test[0][22]))\n",
    "    viewer.add_labels((y_torch_test[0][22]).astype(int))\n",
    "    viewer.add_labels(predN0[0].astype(int), num_colors = 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b6852cea",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
